# 워크플로우 이름
name: Auto Close Issue on Dev Merge

# 실행 조건: pull_request가 닫혔을 때 실행
on:
  pull_request:
    types:
      - closed

# 실행할 작업들
jobs:
  close-issue:
    # 'dev' 브랜치로 병합(merged)된 경우에만 실행
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Close linked issue
        uses: peter-evans/close-issue@v3
        with:
          close-message: '개발 브랜치에 병합되어 이슈를 닫습니다. (Closed by PR)'
          token: ${{ secrets.GITHUB_TOKEN }}